on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 1 * * *" # Every day at 1am UTC (8pm or 9pm ET)

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Use Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Set timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "America/New_York"
    - name: Run scraper script
      run: ./run.sh
      shell: bash
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push